// Auto-generated by CountryDataTools export — do not edit manually.
// Re-generated on every `export --target main` run for US, CA, and MX.
namespace ZipPostLookup.Tests;

internal static class TestCodes
{
    internal static class US
    {
        public const string ExactCode       = "00501";
        public const string ExactPlaceName  = "Holtsville";
        public const string ExactAdmin1Code = "NY";
        public const string ExactTimezone   = "America/New_York";
    }

    internal static class CA
    {
        public const string ExactCode       = "A0A0A0";
        public const string ExactPlaceName  = "Bay Roberts";
        public const string ExactAdmin1Code = "NL";
        public const string ExactTimezone   = "America/St_Johns";
        public const string RangeProbe      = "A1E3H0";
        public const string RangeZpCode     = "A1E0**:A1E6**";
        public const string RangePlaceName  = "St. John's";
        public const string RangeAdmin1Code = "NL";
        public const string RangeTimezone   = "America/St_Johns";
    }

    internal static class MX
    {
        public const string ExactCode       = "00500";
        public const string ExactPlaceName  = "Omitlán de Juárez";
        public const string ExactAdmin1Code = "CMX";
        public const string ExactTimezone   = "America/Mexico_City";
    }

}
